# A collection of aliases for bash
alias ll='ls -ahlF'
alias lt='ls -ahltFr'
alias lth='lt | head'
alias ltt='lt | tail'
alias lr='ls -ahlFR'
alias lls='ll -S | h5'
alias cr='cp -r'
alias rma='rm -rfv'
alias rmv='rm -v'
alias rmac='for f in $(find -name *.pyc -or -name *pycache* -or -name .cache); do rma "$f"; done'
alias rmab='for f in $(find -name ".tox" -or -name "env" -or -name "env_container" -or -name "build" -or -name "dist" | grep -vE "boost|Compose|footprinter|memegen"); do rma "$f"; done'
alias gr='grep -rn'
alias dw='deactivate'
alias sb='source ~/.bashrc'
alias sub='subl ~/.bashrc'
alias suba='subl ~/.bash_aliases'
alias sug='subl ~/.gitconfig'
alias vrc='vims ~/.vimrc'
alias pt='py.test -vvvs'
alias ptc='py.test -vvvs --cov=. --cov-report=html --cov-config=tox.ini'
alias ptv='py.test -vvv'
alias ptl='py.test -vvvs --tb=line'
alias ptlf='py.test -vvvs --last-failed'
alias ptt='py.test'
alias ptx='py.test -vvvs --runxfail'
alias ptk='py.test -vvvs -k'
alias untarbzip='tar -xjvf'
alias untargzip='tar -xzvf'
alias h5='head -n 50'
alias gt='git st'
alias gd='git diff'
alias gs='git ds'
alias gn='git nlog 15'
alias gna='git nlog 15 --all'
alias gp='git plog'
alias guvn='git cm "Update version number between releases"'
alias gurn='git cm "Update release notes"'
alias gput='git push && git push --tags'
alias gpf='git push -f'
alias gfix='git diff --name-only | uniq | xargs subl'
alias cdp='cd ~/projects'
alias pie='pip install -e .'
alias pir='pip install -r requirements.txt'
alias pirt='pip install -r requirements-test.txt'
alias pirb='pip install -r requirements-build.txt'
alias pird='pip install -r requirements-docs.txt'
alias pup='pip install -U pip'
alias pc='pip check'
alias pua='pip freeze | grep -v "^-e" | xargs pip uninstall -y'
alias nh='nautilus .'
alias psd='python setup.py develop'
alias sar='sudo /etc/init.d/apache2 restart'
alias trw='tmux rename-window'
alias tkp='tmux kill-pane -t'
alias tkw='tmux kill-window -t'
alias tks='tmux kill-session -t'
alias tlsc='tmux lsc -F "#{session_name} [#{client_width}x#{client_height}] #{client_activity_string}"'
alias kbb='echo 0 | sudo tee -a /sys/class/leds/smc::kbd_backlight/brightness'
alias edbl='export $(dbus-launch)'
alias camera_on='~/repos/bcwc_pcie/lights_camera_action.sh'
alias camera_off='echo "Removing the facetimehd module..." && sudo rmmod facetimehd'
alias capacity='cat /sys/class/power_supply/BAT0/capacity'
alias vpn_login='sudo openvpn ~/openvpn/client.ovpn'
alias ag='ag -t'
alias less='less -N'
alias tree='tree -I .git'
alias wttr='curl https://wttr.in/"Gold Coast"'
alias vims='vim --servername VIM'
alias vimr='vim --remote-tab'
alias gvims='gvim --servername GVIM'
alias gvimr='gvim --remote-tab'
alias dcl='docker container ls'
alias dil='docker images'
alias dcp='docker container prune -f'
alias dip='docker image prune -f'
alias ducks='du -cksh * .[!.]* | sort -hr'
alias fnmodeoff='sudo bash -c "echo 1 > /sys/module/hid_apple/parameters/fnmode"'
alias fnmodeon='sudo bash -c "echo 2 > /sys/module/hid_apple/parameters/fnmode"'
# Don't forget to run "towncrier --yes --version version"
alias bumpr='bumpversion --allow-dirty --commit --tag release'
alias bumpp='bumpversion --commit patch'
alias release='git add ReleaseNotes.rst unreleased_notes/ && bumpr && bumpp'
alias yy='yes | yay'

# typo catcher
alias pyhton='python'
alias py='python'

# stupid scaling for Atom
# alias atom='atom --force-device-scale-factor=1'

# function for auto window renaming when changing venvs
trw_workon () { trw "$@"; workon "$@"; }
alias workon='trw_workon'

# function for auto window renaming when using ssh
trw_ssh () { trw "$@"; ssh "$@"; }
alias ssh='trw_ssh'
